FROM golang:1.13 as builder
ARG GOARCH

WORKDIR /app

ENV GOOS linux
ENV GOARCH $GOARCH

COPY . .
RUN CGO_ENABLED=0 GOARCH=$GOARCH go build -o main

FROM alpine:3.11
COPY --from=builder /app/main .

ENTRYPOINT ["./main"]
