name: Publish Docker
on: [push]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Login GitHub Registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      -
        name: Buildx test
        run: |
          docker buildx build \
            --load \
            --platform linux/arm/v7,linux/amd64 \
            -t sminamot/hello-world .

      -
        name: Image list
        run: |
          docker images
#      -
#        name: Build image
#        run: |
#          for goarch in amd64 arm; do \
#          echo $goarch; \
#          docker build -t sminamot/hello-world:latest-${goarch} --file Dockerfile-multi --build-arg GOARCH=${goarch} .; \
#          done
#          # latest-amd64 -> latest
#          docker tag sminamot/hello-world:latest-amd64 sminamot/hello-world:latest
#      -
#        name: Push image to DockerHub
#        run: |
#          for tag in latest latest-amd64 latest-arm; do \
#          echo $goarch; \
#          docker push sminamot/hello-world:${tag};\
#          done
