name: Publish Docker
on: [push]
  #  push:
  #    tags:
  #      - v*
  #jobs:
  #  build:
  #    runs-on: ubuntu-latest
  #    steps:
  #    - uses: actions/checkout@master
  #
  #    - name: Publish to Registry
  #      uses: elgohr/Publish-Docker-Github-Action@master
  #      with:
  #        name: sminamot/hello-world
  #        username: ${{ secrets.DOCKER_USERNAME }}
  #        password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/arm/v7 \
            -t github-actions-docker-test \
            --output "type=image,push=false" .
      -
        name: Check Image
        run: |
          docker buildx ls
          docker images
      -
        name: Login GitHub Registry
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      -
        name: Publish to Registry
        run: |
          docker tag github-actions-docker-test sminamot/hello-world:0.0.3
          docker push sminamot/hello-world:0.0.3
