name: Publish Docker
on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Set image tag
      run: |
        # use tag for image_tag, 'v1.2.3' -> '1.2.3'
        IMAGE_TAG=${GITHUB_REF##*/v}
        echo ::set-env name=IMAGE_TAG::${IMAGE_TAG}

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: sminamot/hello-world
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${IMAGE_TAG}"
