name: Publish Docker
on: [push]
  #  push:
  #    tags:
  #      - v*
  #jobs:
  #  build:
  #    runs-on: ubuntu-latest
  #    steps:
  #    - uses: actions/checkout@master
  #
  #    - name: Publish to Registry
  #      uses: elgohr/Publish-Docker-Github-Action@master
  #      with:
  #        name: sminamot/hello-world
  #        username: ${{ secrets.DOCKER_USERNAME }}
  #        password: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      -
        name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      -
        name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x \
            --output "type=image,push=false" .
